version: '3.7'

services:
  badhan-web-docker-service:
    container_name: badhan-web-docker-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/badhan-web'
      - './node_modules:/badhan-web/node_modules/'
    ports:
      - '8080:8080'